name: dbt CI

on:
  workflow_run:
    workflows: ["Weather ETL Pipeline"] # Exact name of the other workflow
    types:
      - completed 
    branches: [main]

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    environment: Production
    env:
      DBT_PROFILES_DIR: /home/runner/.dbt/ # tells dbt where to find profiles.yml

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt
        run: pip install dbt-postgres  # or dbt-bigquery, dbt-postgres, etc.

      - name: Create profiles.yml
        env:
          DB_HOST: ${{ secrets.HOST }}
          DB_USER: ${{ secrets.USER }}
          DB_PASSWORD: ${{ secrets.PASSWORD }}

        run: |
          mkdir -p /home/runner/.dbt
          cat <<EOF > /home/runner/.dbt/profiles.yml
          dbt_weather:
            target: dev
            outputs:
              dev:
                type: postgres
                port: 5432
                database: postgres
                schema: dbt_dev
                threads: 16
                host: $DB_HOST
                user: $DB_USER
                password: $DB_PASSWORD
          EOF

      - name: Debug
        run: |
          echo Hello
          echo $DB_HOST
          echo $DB_USER
          echo $DB_PASSWORD
          cat /home/runner/.dbt/profiles.yml

      - name: dbt deps
        working-directory: ./dbt/dbt_weather
        run: dbt deps

      - name: dbt run
        working-directory: ./dbt/dbt_weather
        run: dbt run