name: Weather ETL Pipeline

on:
  schedule:
    - cron: '* * * * *'   # every hour, at minute 0 (UTC)
  workflow_dispatch:        # lets you trigger it manually from the Actions tab

jobs:
  run-etl:
    runs-on: ubuntu-latest
    environment: Production 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5


      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ETL script
        env:
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: python get_weather.py